apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pipeline-demo
  namespace: rke-pipeline
spec:
  selector:
    matchLabels:
      app: nginx-pipeline-demo
  replicas: 6
  template:
    metadata:
      labels:
        app: nginx-pipeline-demo
    spec:
      containers:
      - name: nginx-pipeline-demo
        imagePullPolicy: Always
        image: ${CICD_IMAGE}:${CICD_GIT_COMMIT}

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-pipeline-demo-service
  namespace: rke-pipeline
  annotations:
    external-dns.alpha.kubernetes.io: 10.10.10.51
spec:
  selector:
    app: nginx
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: 10.10.10.51
  namespace: rke-pipeline
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: 10.10.10.51
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-pipeline-demo-service
              servicePort: 80
