apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: rke-pipeline
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-app
        imagePullPolicy: Always
        image: nginx

---
kind: Service
apiVersion: v1
metadata:
  name: nginx-app
  namespace: rke-pipeline
  annotations:
    external-dns.alpha.kubernetes.io: rkepipeline.n3qa.n3bytes.com
spec:
  selector:
    app: nginx-app
  ports:
    - port: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rkepipeline.n3qa.n3bytes.com
  namespace: rke-pipeline
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: rkepipeline.n3qa.n3bytes.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nginx-service
              servicePort: 80
